### ISSUE TITLE
Task #52793 for BentoBox v2.5.3-SNAPSHOT-b2700 generated an exception

### ISSUE THREAD

**Issue by IAISI** [BentoBoxWorld/IslandFly#119]
### Expected behavior

Unsure.

### Observed/Actual behavior

```

[22:03:03 WARN]: [BentoBox] Task #52793 for BentoBox v2.5.3-SNAPSHOT-b2700 generated an exception
java.lang.UnsupportedOperationException: null
        at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142) ~[?:?]
        at java.base/java.util.ImmutableCollections$AbstractImmutableMap.put(ImmutableCollections.java:1079) ~[?:?]
        at BentoBox.jar/world.bentobox.bentobox.api.metadata.MetaDataAble.lambda$putMetaData$1(MetaDataAble.java:42) ~[BentoBox.jar:?]
        at java.base/java.util.Optional.map(Optional.java:260) ~[?:?]
        at BentoBox.jar/world.bentobox.bentobox.api.metadata.MetaDataAble.putMetaData(MetaDataAble.java:42) ~[BentoBox.jar:?]
        at world.bentobox.border.listeners.PlayerListener.lambda$processEvent$3(PlayerListener.java:79) ~[?:?]
        at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at world.bentobox.border.listeners.PlayerListener.processEvent(PlayerListener.java:77) ~[?:?]
        at world.bentobox.border.listeners.PlayerListener.lambda$onPlayerJoin$0(PlayerListener.java:64) ~[?:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[sakura-1.21.1.jar:1.21.1-DEV-1aef5e1]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[sakura-1.21.1.jar:1.21.1-DEV-1aef5e1]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1734) ~[sakura-1.21.1.jar:1.21.1-DEV-1aef5e1]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:478) ~[sakura-1.21.1.jar:1.21.1-DEV-1aef5e1]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1606) ~[sakura-1.21.1.jar:1.21.1-DEV-1aef5e1]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1311) ~[sakura-1.21.1.jar:1.21.1-DEV-1aef5e1]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:331) ~[sakura-1.21.1.jar:1.21.1-DEV-1aef5e1]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[22:03:03 WARN]: com.destroystokyo.paper.exception.ServerSchedulerException: Task #52793 for BentoBox v2.5.3-SNAPSHOT-b2700 generated an exception
[22:03:03 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:486)
[22:03:03 WARN]:        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1734)
[22:03:03 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:478)
[22:03:03 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1606)
[22:03:03 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1311)
[22:03:03 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:331)
[22:03:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[22:03:03 WARN]: Caused by: java.lang.UnsupportedOperationException
[22:03:03 WARN]:        at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142)
[22:03:03 WARN]:        at java.base/java.util.ImmutableCollections$AbstractImmutableMap.put(ImmutableCollections.java:1079)
[22:03:03 WARN]:        at BentoBox.jar//world.bentobox.bentobox.api.metadata.MetaDataAble.lambda$putMetaData$1(MetaDataAble.java:42)
[22:03:03 WARN]:        at java.base/java.util.Optional.map(Optional.java:260)
[22:03:03 WARN]:        at BentoBox.jar//world.bentobox.bentobox.api.metadata.MetaDataAble.putMetaData(MetaDataAble.java:42)
[22:03:03 WARN]:        at world.bentobox.border.listeners.PlayerListener.lambda$processEvent$3(PlayerListener.java:79)
[22:03:03 WARN]:        at java.base/java.util.Optional.ifPresent(Optional.java:178)
[22:03:03 WARN]:        at world.bentobox.border.listeners.PlayerListener.processEvent(PlayerListener.java:77)
[22:03:03 WARN]:        at world.bentobox.border.listeners.PlayerListener.lambda$onPlayerJoin$0(PlayerListener.java:64)
[22:03:03 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[22:03:03 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475)
[22:03:03 WARN]:        ... 6 more

```

### Steps/models to reproduce

It appears Exception show up right after the player joined the server...

### BentoBox version

> bentobox version
[22:05:19 INFO]: Running PAPER 1.21.1.
[22:05:19 INFO]: (1.21.1-DEV-1aef5e1 (MC: 1.21.1))
[22:05:19 INFO]: BentoBox version: 2.5.3-SNAPSHOT-b2700
[22:05:19 INFO]: Database: JSON
[22:05:19 INFO]: Loaded Game Worlds:
[22:05:19 INFO]: bskyblock_world (BSkyBlock): Overworld, Nether, The End
[22:05:19 INFO]: Loaded Addons:
[22:05:19 INFO]: Bank 1.8.0-SNAPSHOT-b94 (ENABLED)
[22:05:19 INFO]: Biomes 2.2.0-SNAPSHOT-b272 (ENABLED)
[22:05:19 INFO]: Border 4.3.1-SNAPSHOT-b208 (ENABLED)
[22:05:19 INFO]: BSkyBlock 1.18.1 (ENABLED)
[22:05:19 INFO]: Challenges 1.3.2-SNAPSHOT-b560 (ENABLED)
[22:05:19 INFO]: CheckMeOut 1.2.0-SNAPSHOT-b97 (ENABLED)
[22:05:19 INFO]: ControlPanel 1.13.1 (ENABLED)
[22:05:19 INFO]: DimensionalTrees 1.7.0 (ENABLED)
[22:05:19 INFO]: ExtraMobs 1.13 (ENABLED)
[22:05:19 INFO]: IslandFly 1.13.0-SNAPSHOT-b179 (ENABLED)
[22:05:19 INFO]: Likes 2.4.0-SNAPSHOT-b106 (ENABLED)
[22:05:19 INFO]: MagicCobblestoneGenerator 2.5.2-SNAPSHOT-b277 (ENABLED)
[22:05:19 INFO]: TwerkingForTrees 1.5.2 (ENABLED)
[22:05:19 INFO]: Warps 1.15.1-SNAPSHOT-b372 (ENABLED)

**Comment by tastybento** [comment]
Yes, it is. I'll fix.

**Comment by tastybento** [comment]
Latest snapshot should have this fixed.
